### ISSUE TITLE
 BaseCacheManager.getFile (package:flutter_cache_manager/src/cache_manager.dart:120:11)

### ISSUE THREAD

**Issue by yxwandroid** [Baseflow/flutter_cached_network_image#216]
![image](https://user-images.githubusercontent.com/9635493/62120051-74547580-b2f3-11e9-9ec3-62ecc60a7c08.png)

**Comment by renefloor** [comment]
What's the problem? Does the app crash or do you not want this to get printed in the logs?

**Comment by hillelcoren** [comment]
Is there a way to hide these sorts of errors (also 404s)?

**Comment by yrom** [comment]
@renefloor The exception thrown by method BaseCacheManager.getFile was unhandled as expected.

**Comment by JulianHorst** [comment]
+1, we're having the same issue occurring on many of our sessions. We don't fully grasp what this leads to currently.

```
Non-fatal Exception: java.lang.Exception
Connection closed while receiving data
BaseCacheManager.getFile (cache_manager.dart:120)
CachedNetworkImageState._animatedWidget (cached_image_widget.dart:270)
```

**Comment by Gi-lo** [comment]
Furthermore, we are not quite sure how and where we should handle it correctly.

**Comment by yrom** [comment]
I found this issue was happend in this case:  the `CachedNetworkImageState` rebuild with a new image url, for e.g., in a fastscrolling listview, and then the underlying `Stream`  of getting file for the old url in `StreamBuilder` has been unsubscribed, but that `Stream` may throw an exception, the unhandled exception. 
The `getFile` stream should be __cancelled__,  not __unsubscribed__.

**Comment by dungnv2602** [comment]
Any update on this issue? Seeing this error on console all the time is really annoying.

**Comment by babang1da** [comment]
same problem

**Comment by FCMHUB** [comment]
Same...

**Comment by charleshan** [comment]
@yrom's pull request fixes the problem for me.

Here's a temporary solution until the pull request gets merged or until further discussion.
```
dependencies:
  cached_network_image: ^1.1.1
  flutter_cache_manager: ^1.1.1

dependency_overrides:
  flutter_cache_manager:
    git:
      url: https://github.com/yrom/flutter_cache_manager
      ref: feature/close-stream-on-cancel
```
