### ISSUE TITLE
 CacheManager: Connection closed before full header was received

### ISSUE THREAD

**Issue by wangxingxing123654** [Baseflow/flutter_cached_network_image#443]
## 🐛 Bug Report

 CacheManager: Failed to download file from https://harbor.alpha.stylewe.com/image_cache/resize/335x445/image/catalog/2015-04-01/new pic/15-4-1-15-3.JPG with error:
Connection closed before full header was received
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by wangxingxing123654** [comment]
but brower can open it , [pic url](https://harbor.alpha.stylewe.com/image_cache/resize/335x445/image/catalog/2015-04-01/new pic/15-4-1-15-3.JPG)

**Comment by khalidlionel** [comment]
any solutions for this issue ?

**Comment by whatamelon** [comment]
this is really issue. 
when I get over 30 images, some images are stuck and not represent.
Is this issue is flutter's http issue or cache library's issue?

**Comment by Ocelyn** [comment]
same issue here, the fix to change request from https to HTTP is not helping

**Comment by Arley011** [comment]
Same here, pls fix it :)

**Comment by renefloor** [comment]
I think it might be a problem that the server closes the connections when to many images are downloaded at the same time. So I guess it could be solved with queuing as proposed in #453

**Comment by bradsb** [comment]
@renefloor This issue is still occurring on Flutter 1.22.1, with `CachedNetworkImage` 2.3.3

**Comment by renefloor** [comment]
Which version of flutter_cache_manager is in your pubspec.lock?

**Comment by bradsb** [comment]
```yaml
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
```
