### ISSUE TITLE
Latest `master` breaks the library (while using with flutter_driver)

### ISSUE THREAD

**Issue by deimantasa** [Baseflow/flutter_cached_network_image#452]
### Old (and correct) behavior
Fetching packages fine.

### Current behavior
```
Because every version of flutter_driver from sdk depends on process 4.0.0-nullsafety.1 which depends on file ^6.0.0-nullsafety.1, every version of flutter_driver from sdk requires file ^6.0.0-nullsafety.1.
And because cached_network_image >=2.3.0-rc depends on flutter_cache_manager ^1.4.1 which depends on file ^5.1.0, flutter_driver from sdk is incompatible with cached_network_image >=2.3.0-rc.
So, because fluid depends on both cached_network_image ^2.3.1 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because fluid depends on both cached_network_image ^2.3.1 and flutter_driver any from sdk, version solving failed.)
```

I guess both - `cached_network_image` and `flutter_cache_manager` needs to be updated.

### Reproduction steps
1. Create new project;
2. Copy-paste to `pubspec.yaml`
```
name: flutter_app_bug_cached_image
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
```
3. Type `flutter pub get` into terminal

### Configuration

**Flutter doctor**
`Channel master, 1.22.0-10.0.pre.39,`

**EDIT**
After quick checking, issue already exists in `flutter_cache_manager` https://github.com/Baseflow/flutter_cache_manager/issues/216
