### ISSUE TITLE
Operand of null-aware operation '?.' has type 'SchedulerBinding'

### ISSUE THREAD

**Issue by ankitparmar007** [Baseflow/flutter_cached_network_image#732]
## 🐛 Bug Report
**_Warning After upgrading flutter to 3.0.0:_**

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/multi_image_stream_completer.dart:152:22: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.scheduleFrameCallback(_handleAppFrame);
                     ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/cached_network_image_provider.dart:109:29: Warning: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/painting/binding.dart').
      () => PaintingBinding.instance?.imageCache?.evict(key),
                            ^
```

**Comment by MindMayhem** [comment]
https://github.com/imaNNeoFighT/fl_chart/issues/997
https://github.com/Milad-Akarie/auto_route_library/issues/1065

**Comment by beaurepair** [comment]
https://github.com/Baseflow/flutter_cached_network_image/pull/727

**Comment by C1rdec** [comment]
https://github.com/Baseflow/flutter_cached_network_image/pull/734

**Comment by noga-dev** [comment]
Add this to pubspec for now:

```yaml
dependency_overrides:
  cached_network_image:
    git:
      url: https://github.com/XuannThucc/flutter_cached_network_image.git
      path: cached_network_image
      ref: ff72f00f142f13d889d7549e013af91cb0b523ab
```
